import { StyleSheet } from "react-native"

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: "center",
    backgroundColor: "#F0F5F9",
  },
  question: {
    width: "90%",
    marginTop: 8,
  },
  hero: {
    fontSize: 24,
    fontWeight: "bold",
    marginBottom: 20,
  },
  answerButton: {
    backgroundColor: "#fff",
    borderRadius: 8,
    paddingVertical: 12,
    paddingHorizontal: 16,
    marginVertical: 5,
    elevation: 1,
    flexDirection: "row",
    alignItems: "center",
    gap: 16,
  },
  selectedAnswerButton: {
    backgroundColor: "#0085ff",
    borderRadius: 8,
    paddingVertical: 12,
    paddingHorizontal: 16,
    marginVertical: 5,
    elevation: 1,
    flexDirection: "row",
    alignItems: "center",
    gap: 16,
  },
  correctAnswerButton: {
    backgroundColor: "#03C988",
    borderRadius: 8,
    paddingVertical: 12,
    paddingHorizontal: 16,
    marginVertical: 5,
    elevation: 1,
    flexDirection: "row",
    alignItems: "center",
    gap: 16,
  },
  incorrectAnswerButton: {
    backgroundColor: "#ff4d4d",
    borderRadius: 8,
    paddingVertical: 12,
    paddingHorizontal: 16,
    marginVertical: 5,
    elevation: 1,
    flexDirection: "row",
    alignItems: "center",
    gap: 16,
  },
  viewAswerLetter: {
    width: 36,
    height: 36,
    borderRadius: 100,
    backgroundColor: "#F0F5F9",
    alignItems: "center",
    justifyContent: "center",
  },
  answerText: {
    fontSize: 18,
  },
  selectedAnswerText: {
    color: "#fff",
  },
  selectedAnswerLetter: {
    backgroundColor: "#fff",
  },
  viewAnswerLetter: {
    width: 36,
    height: 36,
    borderRadius: 100,
    backgroundColor: "#F0F5F9",
    alignItems: "center",
    justifyContent: "center",
  },
  answerLetter: {
    fontSize: 16,
    fontWeight: "bold",
    textAlign: "center",
  },
  selectedAnswerText: {
    color: "#fff",
  },
  confirmButton: {
    bottom: 32,
    position: "absolute",
    backgroundColor: "#0085ff",
    paddingVertical: 16,
    borderRadius: 5,
    marginTop: 20,
    width: "90%",
  },
  confirmText: {
    color: "#ffffff",
    fontSize: 18,
    fontWeight: "bold",
    textAlign: "center",
  },
  resultText: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#000",
    marginTop: 10,
  },
  progressBarContainer: {
    width: "100%",
    height: 10,
    backgroundColor: "#e0e0e0",
  },
  progressBar: {
    height: "100%",
    backgroundColor: "#0085ff",
    borderRadius: 10,
  },
  completionContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  completionText: {
    fontSize: 24,
    fontWeight: "bold",
  },
})
